name: pb_test1

on: workflow_dispatch

jobs:
  test:
    runs-on: windows-latest
    steps:

#      - name: Test env
#        run: |
#         echo github.action_path    : ${{github.action_path}}
 #        echo env.GITHUB_WORKSPACE  : ${{env.GITHUB_WORKSPACE}}
 #        echo env.SOLUTION_FILE_PATH  : ${{env.SOLUTION_FILE_PATH}}
 #       shell: cmd

        
      - uses: actions/checkout@v3
      - name: Setup PB Compiler
        uses: LinXP/pb_compiller/@main



  #    - name: Ched dir2
  #      run: ls '%PUREBASIC_HOME%\Compilers\'
  #      shell: cmd

      - name: Compiler test script
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: '"C:\Program Files\PureBasic\Compilers\pbcompilerc.exe" "OpenWindow.pb"'
   #     run: '%PUREBASIC_HOME%\Compilers\pbcompilerc.exe'
        # run: '%PUREBASIC_HOME%\Compilers\pbcompilerc.exe %GITHUB_WORKSPACE%\OpenWindow.pb'
        shell: cmd

      - name: Ched dir1
        run: ls  -R
        shell: cmd

      - name: Ched dir2
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: ls  -R
        shell: cmd

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
         name: test
         path: .

 #      - name: Run compiler exe
 #        working-directory: ${{env.GITHUB_WORKSPACE}}
 #        run: 'PureBasic.exe'
 #        shell: cmd
        

        
      

        
#      - name: Compiler test script
#        run: '%AUTOIT_COMPILER_TOOLKIT%\SciTe\AutoIt3Wrapper\AutoIt3Wrapper.exe /NoStatus /prod /in test.au3'
#        shell: cmd
        
#       - name: Run compiler exe
 #        run: '%GITHUB_WORKSPACE%\test.exe'
#         shell: cmd
